[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["corepack pnpm@12.3.4 install --frozen-lockfile"]

[phases.build]
cmds = ["corepack pnpm@12.3.4 run build"]

[start]
cmd = "node ./build/index.js"
